require 'spec_helper'

# This spec was generated by rspec-rails when you ran the scaffold generator.
# It demonstrates how one might use RSpec to specify the controller code that
# was generated by Rails when you ran the scaffold generator.
#
# It assumes that the implementation code is generated by the rails scaffold
# generator.  If you are using any extension libraries to generate different
# controller code, this generated spec may or may not pass.
#
# It only uses APIs available in rails and/or rspec-rails.  There are a number
# of tools you can use to make these specs even more expressive, but we're
# sticking to rails and rspec-rails APIs to keep things simple and stable.
#
# Compared to earlier versions of this generator, there is very limited use of
# stubs and message expectations in this spec.  Stubs are only used when there
# is no simpler way to get a handle on the object needed for the example.
# Message expectations are only used when there is no simpler way to specify
# that an instance is receiving a specific message.

describe AdvisesController do
  render_views
  # This should return the minimal set of attributes required to create a valid
  # Advise. As you add validations to Advise, be sure to
  # update the return value of this method accordingly.
  def valid_attributes
    {:content => "test advise"}
  end

  describe "GET index" do
    it "assigns all advises as @advises" do
      advise = Advise.create! valid_attributes
      get :index
      assigns(:advises).should eq([advise])
    end
  end

  describe "POST create" do
    describe "with valid params" do
      it "creates a new Advise" do
        expect {
          post :create, :advise => valid_attributes
        }.to change(Advise, :count).by(1)
      end

      it "assigns a newly created advise as @advise" do
        post :create, :advise => valid_attributes
        assigns(:advise).should be_a(Advise)
        assigns(:advise).should be_persisted
      end

      it "redirects to the created advise" do
        post :create, :advise => valid_attributes
        response.should redirect_to(advises_path)
      end
    end

    describe "with invalid params" do
      it "assigns a newly created but unsaved advise as @advise" do
        # Trigger the behavior that occurs when invalid params are submitted
        Advise.any_instance.stub(:save).and_return(false)
        post :create, :advise => {}
        assigns(:advise).should be_a_new(Advise)
      end

      it "re-renders the 'new' template" do
        # Trigger the behavior that occurs when invalid params are submitted
        Advise.any_instance.stub(:save).and_return(false)
        post :create, :advise => {}
        response.should redirect_to(advises_path)
      end
    end
  end

#  describe "DELETE destroy" do
#    it "destroys the requested advise" do
#      advise = Advise.create! valid_attributes
#      expect {
#        delete :destroy, :id => advise.id
#      }.to change(Advise, :count).by(-1)
#    end
#
#    it "redirects to the advises list" do
#      advise = Advise.create! valid_attributes
#      delete :destroy, :id => advise.id
#      response.should redirect_to(advises_url)
#    end
#  end

end
