require 'spec_helper'

# This spec was generated by rspec-rails when you ran the scaffold generator.
# It demonstrates how one might use RSpec to specify the controller code that
# was generated by Rails when you ran the scaffold generator.
#
# It assumes that the implementation code is generated by the rails scaffold
# generator.  If you are using any extension libraries to generate different
# controller code, this generated spec may or may not pass.
#
# It only uses APIs available in rails and/or rspec-rails.  There are a number
# of tools you can use to make these specs even more expressive, but we're
# sticking to rails and rspec-rails APIs to keep things simple and stable.
#
# Compared to earlier versions of this generator, there is very limited use of
# stubs and message expectations in this spec.  Stubs are only used when there
# is no simpler way to get a handle on the object needed for the example.
# Message expectations are only used when there is no simpler way to specify
# that an instance is receiving a specific message.

describe MyspacesController do

  # This should return the minimal set of attributes required to create a valid
  # Myspace. As you add validations to Myspace, be sure to
  # update the return value of this method accordingly.
  def valid_attributes
    {}
  end

  describe "GET index" do
    it "assigns all myspaces as @myspaces" do
      myspace = Myspace.create! valid_attributes
      get :index
      assigns(:myspaces).should eq([myspace])
    end
  end

  describe "GET show" do
    it "assigns the requested myspace as @myspace" do
      myspace = Myspace.create! valid_attributes
      get :show, :id => myspace.id
      assigns(:myspace).should eq(myspace)
    end
  end

  describe "GET new" do
    it "assigns a new myspace as @myspace" do
      get :new
      assigns(:myspace).should be_a_new(Myspace)
    end
  end

  describe "GET edit" do
    it "assigns the requested myspace as @myspace" do
      myspace = Myspace.create! valid_attributes
      get :edit, :id => myspace.id
      assigns(:myspace).should eq(myspace)
    end
  end

  describe "POST create" do
    describe "with valid params" do
      it "creates a new Myspace" do
        expect {
          post :create, :myspace => valid_attributes
        }.to change(Myspace, :count).by(1)
      end

      it "assigns a newly created myspace as @myspace" do
        post :create, :myspace => valid_attributes
        assigns(:myspace).should be_a(Myspace)
        assigns(:myspace).should be_persisted
      end

      it "redirects to the created myspace" do
        post :create, :myspace => valid_attributes
        response.should redirect_to(Myspace.last)
      end
    end

    describe "with invalid params" do
      it "assigns a newly created but unsaved myspace as @myspace" do
        # Trigger the behavior that occurs when invalid params are submitted
        Myspace.any_instance.stub(:save).and_return(false)
        post :create, :myspace => {}
        assigns(:myspace).should be_a_new(Myspace)
      end

      it "re-renders the 'new' template" do
        # Trigger the behavior that occurs when invalid params are submitted
        Myspace.any_instance.stub(:save).and_return(false)
        post :create, :myspace => {}
        response.should render_template("new")
      end
    end
  end

  describe "PUT update" do
    describe "with valid params" do
      it "updates the requested myspace" do
        myspace = Myspace.create! valid_attributes
        # Assuming there are no other myspaces in the database, this
        # specifies that the Myspace created on the previous line
        # receives the :update_attributes message with whatever params are
        # submitted in the request.
        Myspace.any_instance.should_receive(:update_attributes).with({'these' => 'params'})
        put :update, :id => myspace.id, :myspace => {'these' => 'params'}
      end

      it "assigns the requested myspace as @myspace" do
        myspace = Myspace.create! valid_attributes
        put :update, :id => myspace.id, :myspace => valid_attributes
        assigns(:myspace).should eq(myspace)
      end

      it "redirects to the myspace" do
        myspace = Myspace.create! valid_attributes
        put :update, :id => myspace.id, :myspace => valid_attributes
        response.should redirect_to(myspace)
      end
    end

    describe "with invalid params" do
      it "assigns the myspace as @myspace" do
        myspace = Myspace.create! valid_attributes
        # Trigger the behavior that occurs when invalid params are submitted
        Myspace.any_instance.stub(:save).and_return(false)
        put :update, :id => myspace.id, :myspace => {}
        assigns(:myspace).should eq(myspace)
      end

      it "re-renders the 'edit' template" do
        myspace = Myspace.create! valid_attributes
        # Trigger the behavior that occurs when invalid params are submitted
        Myspace.any_instance.stub(:save).and_return(false)
        put :update, :id => myspace.id, :myspace => {}
        response.should render_template("edit")
      end
    end
  end

  describe "DELETE destroy" do
    it "destroys the requested myspace" do
      myspace = Myspace.create! valid_attributes
      expect {
        delete :destroy, :id => myspace.id
      }.to change(Myspace, :count).by(-1)
    end

    it "redirects to the myspaces list" do
      myspace = Myspace.create! valid_attributes
      delete :destroy, :id => myspace.id
      response.should redirect_to(myspaces_url)
    end
  end

end
